version: "3.7"

services:
  db_odontocli: 
    image: postgres
    container_name: db_odontocli
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_odontocli
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    command: >
      sh -c "yarn &&
             yarn typeorm migration:run &&
             yarn seed:cidade &&
             yarn seed:paciente &&
             yarn dev"
    container_name: backend_odontocli
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_odontocli
    restart: on-failure
    depends_on:
      - db_odontocli
volumes:
  pgdata:
    driver: local