version: "3.7"

services:
  db_odontocli: 
    image: postgres
    container_name: db_odontocli
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_odontocli
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: odontocli
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_odontocli
    depends_on:
      - database_odontocli

volumes:
  pgdata:
    driver: local