import { createConnection } from "typeorm";
import { v4 as uuidv4 } from "uuid";

async function create() {
  const connection = await createConnection();

  await connection.query(
    `INSERT INTO cidade("idCidade", "nomeCidade", "uf")
      VALUES('${uuidv4()}', 'Afonso Cláudio', 'ES'),
      ('${uuidv4()}', 'Água Doce do Norte', 'ES'),
      ('${uuidv4()}', 'Águia Branca', 'ES'),
      ('${uuidv4()}', 'Alegre', 'ES'),
      ('${uuidv4()}', 'Alfredo Chaves', 'ES'),
      ('${uuidv4()}', 'Alto Rio Novo', 'ES'),
      ('${uuidv4()}', 'Anchieta', 'ES'),
      ('${uuidv4()}', 'Apiacá', 'ES'),
      ('${uuidv4()}', 'Aracruz', 'ES'),
      ('${uuidv4()}', 'Atílio Vivácqua', 'ES'),
      ('${uuidv4()}', 'Baixo Guandu', 'ES'),
      ('${uuidv4()}', 'Barra de São Francisco', 'ES'),
      ('${uuidv4()}', 'Boa Esperança', 'ES'),
      ('${uuidv4()}', 'Bom Jesus do Norte', 'ES'),
      ('${uuidv4()}', 'Brejetuba', 'ES'),
      ('${uuidv4()}', 'Cachoeiro de Itapemirim', 'ES'),
      ('${uuidv4()}', 'Cariacica', 'ES'),
      ('${uuidv4()}', 'Castelo', 'ES'),
      ('${uuidv4()}', 'Colatina', 'ES'),
      ('${uuidv4()}', 'Conceição da Barra', 'ES'),
      ('${uuidv4()}', 'Conceição do Castelo', 'ES'),
      ('${uuidv4()}', 'Divino de São Lourenço', 'ES'),
      ('${uuidv4()}', 'Domingos Martins', 'ES'),
      ('${uuidv4()}', 'Dores do Rio Preto', 'ES'),
      ('${uuidv4()}', 'Ecoporanga', 'ES'),
      ('${uuidv4()}', 'Fundão', 'ES'),
      ('${uuidv4()}', 'Governador Lindenberg', 'ES'),
      ('${uuidv4()}', 'Guaçuí', 'ES'),
      ('${uuidv4()}', 'Guarapari', 'ES'),
      ('${uuidv4()}', 'Ibatiba', 'ES'),
      ('${uuidv4()}', 'Ibiraçu', 'ES'),
      ('${uuidv4()}', 'Ibitirama', 'ES'),
      ('${uuidv4()}', 'Iconha', 'ES'),
      ('${uuidv4()}', 'Irupi', 'ES'),
      ('${uuidv4()}', 'Itaguaçu', 'ES'),
      ('${uuidv4()}', 'Itapemirim', 'ES'),
      ('${uuidv4()}', 'Itarana', 'ES'),
      ('${uuidv4()}', 'Iúna', 'ES'),
      ('${uuidv4()}', 'Jaguaré', 'ES'),
      ('${uuidv4()}', 'Jerônimo Monteiro', 'ES'),
      ('${uuidv4()}', 'João Neiva', 'ES'),
      ('${uuidv4()}', 'Laranja da Terra', 'ES'),
      ('${uuidv4()}', 'Linhares', 'ES'),
      ('${uuidv4()}', 'Mantenópolis', 'ES'),
      ('${uuidv4()}', 'Marataízes', 'ES'),
      ('${uuidv4()}', 'Marechal Floriano', 'ES'),
      ('${uuidv4()}', 'Marilândia', 'ES'),
      ('${uuidv4()}', 'Mimoso do Sul', 'ES'),
      ('${uuidv4()}', 'Montanha', 'ES'),
      ('${uuidv4()}', 'Mucurici', 'ES'),
      ('${uuidv4()}', 'Muniz Freire', 'ES'),
      ('${uuidv4()}', 'Muqui', 'ES'),
      ('${uuidv4()}', 'Nova Venécia', 'ES'),
      ('${uuidv4()}', 'Pancas', 'ES'),
      ('${uuidv4()}', 'Pedro Canário', 'ES'),
      ('${uuidv4()}', 'Pinheiros', 'ES'),
      ('${uuidv4()}', 'Piúma', 'ES'),
      ('${uuidv4()}', 'Ponto Belo', 'ES'),
      ('${uuidv4()}', 'Presidente Kennedy', 'ES'),
      ('${uuidv4()}', 'Rio Bananal', 'ES'),
      ('${uuidv4()}', 'Rio Novo do Sul', 'ES'),
      ('${uuidv4()}', 'Santa Leopoldina', 'ES'),
      ('${uuidv4()}', 'Santa Maria de Jetibá', 'ES'),
      ('${uuidv4()}', 'Santa Teresa', 'ES'),
      ('${uuidv4()}', 'São Domingos do Norte', 'ES'),
      ('${uuidv4()}', 'São Gabriel da Palha', 'ES'),
      ('${uuidv4()}', 'São José do Calçado', 'ES'),
      ('${uuidv4()}', 'São Mateus', 'ES'),
      ('${uuidv4()}', 'São Roque do Canaã', 'ES'),
      ('${uuidv4()}', 'Serra', 'ES'),
      ('${uuidv4()}', 'Sooretama', 'ES'),
      ('${uuidv4()}', 'Vargem Alta', 'ES'),
      ('${uuidv4()}', 'Venda Nova do Imigrante', 'ES'),
      ('${uuidv4()}', 'Viana', 'ES'),
      ('${uuidv4()}', 'Vila Pavão', 'ES'),
      ('${uuidv4()}', 'Vila Valério', 'ES'),
      ('${uuidv4()}', 'Vila Velha', 'ES'),
      ('${uuidv4()}', 'Vitória', 'ES')
    `
  );
  await connection.close();
}
create().then(() => console.log("A tabela 'cidade' foi populada com sucesso!"));
